# Generated by Django 4.2.3 on 2023-09-20 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("factors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="factors",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
        ),
        migrations.AddField(
            model_name="factors",
            name="sign_pleasant_habit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="factors.habit"
            ),
        ),
    ]
